name: Deploy a Surge
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar Surge
        run: npm install -g surge
      - name: Desplegar
        run: surge ./ --project ./ --domain primer-parcial.surge.sh --token ${{ secrets.SURGE_TOKEN }}
